### ISSUE TITLE
JsonWebToken UndefinedFunctionError

### ISSUE THREAD

**Issue by mquickform** [garyf/json_web_token_ex#12]
Hi, this may very well be a noob question, but I am completely stuck with the verify function.

I'm basically doing this:
`JsonWebToken.verify("a_working_jwt_here", %{alg: "HS256", key: "a_corresponding_key_that_is_also_good_here"})`

everything is working beautifully on my dev machine (osx), but on the production server (ubuntu 14.04) it just doesn't work. I am certain that the token is good and have verified it several times on jwt.io.

On the server I get this exception:

`%UndefinedFunctionError{arity: 2, function: :verify, module: JsonWebToken, reason: nil}`

I am at a complete loss, (I've just started with Elixir).

Server is running Elixir 1.3.2.

Any help is much appreciated! 

Thanks in advance, Marcus

**Comment by garyf** [comment]
off the top of my head, with the UndefinedFunctionError, I would suspect a corrupt Elixir installation on the server; are you able to create a new token on that server?

**Comment by mquickform** [comment]
Hi thanks, for your reply, I will try and reinstall that and see how it works. And no, I haven't created any tokens on the server, it's just verifying - so I will try that to and report back! Thanks.
