### ISSUE TITLE
Erlang OTP 20 breaks JsonWebToken.Algorithm.Rsa.validate_key_size/1

### ISSUE THREAD

**Issue by BrendonPierson** [garyf/json_web_token_ex#20]
It appears the latest erlang release has removed `:crypto.mpint/1`.  This is causing the `JsonWebToken.Algorithm.Rsa.validate_key_size/1` to break.  I think we will need a work around for validating key size.

**Comment by lachezar** [comment]
As a temporary solution I created a erl file with the `mpint/1` implementation. I am not sure if there is a proper function in crypto or in other modules which can replace `mpint/1` (I am not experienced with Erlang), but I can make a PR if this solution is good enough.

https://github.com/lachezar/json_web_token_ex/commit/e9b0fafdedcceb2c19505ab864f662995e9ce594

**Comment by BrendonPierson** [comment]
I've played around with it a bit and it looks like `:crypto.mpint/1` was just moved to `:ssh_bits.mpint/1`.  I'm not sure on the best practice here, but It's probably wise to run some logic that picks the correct version based on the erlang version.

Here is a simple workaround that runs a check for the Erlang version and picks the right function -> #21

**Comment by lachezar** [comment]
Looks very clean and nice!!
