### ISSUE TITLE
Improve RS256 documentation

### ISSUE THREAD

**Issue by ohanhi** [garyf/json_web_token_ex#9]
Hey, thanks for this great lib!

I had a bit of trouble switching from HS256 to RS256, as the documentation only states to include `< RSA private key >` in the options. I think it would be worthwhile to reformat this into e.g. the following:

``` elixir
# sign with RSA SHA256 algorithm
private_key = JsonWebToken.Algorithm.RsaUtil.private_key("path/to/", "key.pem")
opts = %{
  alg: "RS256",
  key: private_key
}
```

**Comment by garyf** [comment]
closed with v0.2.5, bc73974
